# Generated by Django 5.0 on 2024-10-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ticket_category',
        ),
    ]
