# Generated by Django 5.1 on 2024-08-20 06:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Concert', 'Concert'), ('Conference', 'Conference'), ('Festival', 'Festival'), ('Workshop', 'Workshop'), ('Sports', 'Sports'), ('Theatre', 'Theatre'), ('Others', 'Others')], max_length=50)),
                ('custom_category', models.CharField(blank=True, help_text="If 'Others' is selected, specify the category here.", max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Optional, only required for multi-day events.', null=True)),
                ('venue_name', models.CharField(max_length=255)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional sale price.', max_digits=10, null=True)),
                ('inventory', models.BooleanField(default=False, help_text='Enable if you want to manage inventory (tickets available).')),
                ('tickets_available', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='event_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tickets_available', models.PositiveIntegerField(blank=True, help_text='Optional, only required if inventory management is enabled.', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='events.event')),
            ],
        ),
    ]
