# Generated by Django 5.1 on 2024-08-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_cart_user_cart_customer_cart_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='category_tickets_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
