# Generated by Django 5.0 on 2024-10-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posagent',
            name='is_posagent',
            field=models.BooleanField(default=True),
        ),
    ]
