# Generated by Django 5.0 on 2024-10-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_posagent_is_posagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='posagent',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='posagent',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
