# Generated by Django 5.1 on 2024-08-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
    ]
