# Generated by Django 5.1 on 2024-08-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_customer',
        ),
    ]
