# Generated by Django 5.1 on 2024-08-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_vendor',
            field=models.BooleanField(default=True),
        ),
    ]
