# Generated by Django 5.1 on 2024-08-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='verification_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
