# Generated by Django 5.1 on 2024-08-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
